networks:
  traefik:
    external: true

services:
  api:
    image: ghcr.io/jonastroeltsch/pw4:latest
    networks:
      - traefik
    expose:
      - 7070
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## HTTPS
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.rule=Host(`${DOMAIN_NAME}`)
